server:
  port: 8081
spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FallDetection?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: holmes96
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: holmes96
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

mybatis-plus:
  type-aliases-package: com.falldetection.backend.entity # 别名扫描包